ATHOME_UPLOAD_STORE_FILE=prod_keystore.jks
ATHOME_UPLOAD_KEY_ALIAS=@home_prod
ATHOME_UPLOAD_STORE_PASSWORD=android
ATHOME_UPLOAD_KEY_PASSWORD=android

UMII_UPLOAD_STORE_FILE=my-umii-upload-key.keystore
UMII_UPLOAD_KEY_ALIAS=my-umii-key-alias
UMII_UPLOAD_STORE_PASSWORD=cLcPu22
UMII_UPLOAD_KEY_PASSWORD=cLcPu22

PROFALUX_UPLOAD_STORE_FILE=calypshome-release-key.keystore
PROFALUX_UPLOAD_KEY_ALIAS=calypshome
PROFALUX_UPLOAD_STORE_PASSWORD=olivierpariscalypshome2017
PROFALUX_UPLOAD_KEY_PASSWORD=olivierpariscalypshome2017

STELLAGROUP_UPLOAD_STORE_FILE=stellacalypshome-release-key.keystore
STELLAGROUP_UPLOAD_KEY_ALIAS=stellacalypshome
STELLAGROUP_UPLOAD_STORE_PASSWORD=stella
STELLAGROUP_UPLOAD_KEY_PASSWORD=stella
