const NOTIFICATION_PUSH_ADD = 'NOTIFICATIONS::PUSH::ADD';
const NOTIFICATION_PUSH_DELETE = 'NOTIFICATIONS::PUSH::DELETE';
const NOTIFICATION_PUSH_SET_TOKEN = "NOTIFICATION::PUSH::SET::TOKEN";
const NOTIFICATION_PUSH_COLD_START = "NOTIFICATION::PUSH::COLD::START";
const NOTIFICATION_PUSH_IN_BACKGROUND = "NOTIFICATION::PUSH::IN::BACKGROUND";
const NOTIFICATION_PUSH_FULLSCREEN_ANDROID = "NOTIFICATION::PUS::FULLSCREEN::ANDROID"

export {
    NOTIFICATION_PUSH_ADD,
    NOTIFICATION_PUSH_DELETE,
    NOTIFICATION_PUSH_SET_TOKEN,
    NOTIFICATION_PUSH_COLD_START,
    NOTIFICATION_PUSH_IN_BACKGROUND,
    NOTIFICATION_PUSH_FULLSCREEN_ANDROID  
}