const OBJECTS_FILL = 'OBJECTS::FILL'
const OBJECTS_RELOAD = 'OBJECTS::RELOAD';
const OBJECT_UPDATE = 'OBJECT::UPDATE'
const OBJECT_UPDATE_STATUSES = 'OBJECT::UPDATE::STATUSES'

const OBJECT_DELETE = "OBJECT::DELETE"
const OBJECTS_ADD = "OBJECTS::ADD"
const OBJECT_ADD = "OBJECT::ADD"
const OBJECT_UPDATE_FROM_WEBSOCKET = 'OBJECT::UPDATE::FROM::WEBSOCKET'
const OBJECT_UPDATE_PROPERTY_FROM_WEBSOCKET = 'OBJECT::UPDATE::PROPERTY::FROM::WEBSOCKET'
const OBJECT_UPDATE_PROPERTY = 'OBJECT::UPDATE::PROPERTY';
const OBJECT_UPDATE_PARAMETER = 'OBJECT::UPDATE::PARAMETER';
const OBJECT_EXECUTE_ACTION = 'OBJECT::EXECUTE//ACTION';
const GROUP_ADD = 'GROUP::ADD';
const GROUP_UPDATE = "GROUP::UPDATE";
const SCENARIO_NOTIFICATION_UPDATE = "SCENARIO::NOTIFICATION::UPDATE";
const OBJECT_UPDATE_FLAGS = "OBJECT::UPDATE::FLAGS";
const OBJECT_SET_SCHEDULE_DATAS = "OBJECT::SET::SCHEDULE::DATAS";
const  OBJECT_SET_SCHEDULE_ACTIVE = "OBJECT::SET::SCHEDULE::ACTIVE";
const HEATER_PROGRAM_DEACTIVATE = "HEATER::PROGRAM::DEACTIVATE";
const OBJECT_UPDATE_RDEPENDENCY="OBJECT::UPDATE::RDEPENDENCY";
const GROUP_UPDATE_STATUS="GROUP::UPDATE::STATUS";

const RUNTIME_DATAS = "OBJECT::RUNTIME::DATAS";
const GROUP_UPDATE_COMPONENTS="GROUP::UPDATE::COMPONENTS";
const OBJECT_UPDATE_RDEPENDENCIES="OBJECT::UPDATE::RDEPENDENCIES";
const GROUP_UPDATE_COMPONENT_TYPES="GROUP::UPDATE::COMPONENT::TYPES";
const GROUP_UPDATE_TRAIS="GROUP::UPDATE::TRAITS";
const GATEWAY_ADD ="GATEWAY::ADD";
const ADD_SCHEDULER_TASK ="ADD::SCHEDULER::TASK";
const ECO_CONFORT_UPDATE_PARAMETER = "ECO::CONFORT::UPDATE::PARAMETER";
const WEEKLYPLANNER_UPDATE_DAYSOFWEEK = "WEEKLYPLANNER::UPDATE::DAYSOFWEEK";


// needed for pairing without direct return (i.e. Zigbee added to server by the zigbee gateway)
const PAIRING = "OBJECT::PAIRING::BT"
const PAIRING_REMOVE = "OBJECT::PAIRING::REMOVE::BT";
//========================================================
const MAINTENANCE_ADD = "OBJECT::MAINTENANCE_ADD";
const MAINTENANCE_REMOVE = "OBJECT::MAINTENANCE_REMOVE";


export {
        OBJECTS_FILL,
        OBJECTS_RELOAD,
        OBJECTS_ADD,
        OBJECT_ADD,
        OBJECT_UPDATE,
        OBJECT_UPDATE_STATUSES,
        OBJECT_UPDATE_PARAMETER,
        OBJECT_UPDATE_FLAGS,       
        OBJECT_UPDATE_FROM_WEBSOCKET,
        OBJECT_UPDATE_PROPERTY_FROM_WEBSOCKET,
        OBJECT_UPDATE_PROPERTY,
        OBJECT_DELETE,
        OBJECT_EXECUTE_ACTION,
        GROUP_ADD,
        GROUP_UPDATE,
        SCENARIO_NOTIFICATION_UPDATE,
        OBJECT_SET_SCHEDULE_DATAS,
        OBJECT_SET_SCHEDULE_ACTIVE,
        HEATER_PROGRAM_DEACTIVATE,
        OBJECT_UPDATE_RDEPENDENCY,
        GROUP_UPDATE_STATUS,
        RUNTIME_DATAS,
        PAIRING,PAIRING_REMOVE,
        MAINTENANCE_ADD,MAINTENANCE_REMOVE,
        GROUP_UPDATE_COMPONENTS,
        GROUP_UPDATE_COMPONENT_TYPES,
        GROUP_UPDATE_TRAIS,
        GATEWAY_ADD,
        OBJECT_UPDATE_RDEPENDENCIES,
        ADD_SCHEDULER_TASK,
        ECO_CONFORT_UPDATE_PARAMETER,
        WEEKLYPLANNER_UPDATE_DAYSOFWEEK
}